### ISSUE TITLE
Icon request: gmusicbrowser

### ISSUE THREAD

**Issue by quassy** [mank319/elementaryPlus#131]
[Relevant Google+ post](https://plus.google.com/116093572651901735150/posts/MgewUTMWFHW).

Original icon from their website: 
![Original icon](https://gmusicbrowser.org/icons/icon.png)

Maybe the [icon from elementary-add](https://github.com/varlesh/elementary-add/blob/master/elementary-add/apps/48/gmusicbrowser.svg) could be used as base (only 48px atm).

**Comment by rootsandculture** [comment]
https://github.com/varlesh/elementary-add/blob/master/elementary-add/apps/48/gmusicbrowser.svg

Is there a possibility for using that icon? Looks much integrated than the other one.

**Comment by quassy** [comment]
I linked the exact same image in my original post ;). Yes it is possible, but we would still need the other sizes of that icon (16, 24, 32, 128 px).

**Comment by rootsandculture** [comment]
Sorry, I can't help creating those icons :(
