### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by phsleague** [mank319/elementaryPlus#133]
Hello,

I installed Spotify, and I also ran the elementaryplus install script and toggled to apply the core and spotify icon and I applied it. However the Spotify icon remains green on the taskbar. Please advise. Thanks.

**Comment by cybre** [comment]
Run `rm -rf /tmp/sni-qt_spotify_*` in your terminal. After that, run
Spotify again and try installing the icon again.

**Comment by phsleague** [comment]
I did what you recommended, rm sni-qt_spotify, then ran the install script again and this time it asked me to install the patched sni-qt, clicked yes. Ran Spotify again and icon is no longer green. Thanks for the help.
