### ISSUE TITLE
elementary-add final release

### ISSUE THREAD

**Issue by palob** [mank319/elementaryPlus#134]
Three weeks ago the [elementary-add](https://github.com/varlesh/elementary-add) repository received a [commit](https://github.com/varlesh/elementary-add/commit/635645bb55a1ba7287c04d44e5c9fe6ff7384a8e) labelled *Final release!*. 

It hasn't received any commits since indeed as the author seems to have moved on to other [projects](https://github.com/varlesh/papirus-icon-theme).

So maybe it's time to incorporate appropriate icons from there?

The licence is *GPLv3* and all? contributors are credited.

**Comment by quassy** [comment]
Yes but... we would need to create the other sizes as e.g. all app icons are only in 48px.

**Comment by RafaelCz** [comment]
I don't see anything we could merge. 
As the [Human interface Guidelines of elementary OS](https://elementary.io/de/docs/human-interface-guidelines#launcher-icons) state, there should be separate icons for all possible display sizes, including 32, 48, 64, and 128 pixels.

**Comment by palob** [comment]
I for one think the icons could be an improvement even without recreating all sizes.
I mean the default app icons

**Comment by quassy** [comment]
I agree with @RafaelCz, there is nothing to merge directly, only some icons to build upon (some others I think don't really fit). We should try to follow the same high standards as elementary itself. If we ship only 48px the icons will look quite bad in some places (e.g. Slingshot).

**Comment by cybre** [comment]
Closing for now.
