### ISSUE TITLE
ownCloud indicator icons don't change

### ISSUE THREAD

**Issue by RafaelCz** [mank319/elementaryPlus#137]
I'm using ownCloud client version 1.8.1 and the indicator icons provided by elementary+ don't change.

**Comment by cybre** [comment]
Going to investigate.

**Comment by RafaelCz** [comment]
It seems we need to change them with patched sni-qt...

**Comment by cybre** [comment]
Well, yes. You can install them via the installer but the new icons will
only show when the monochrome option is ticked in Owncloud settings. I'll
change that tomorrow.

**Comment by cybre** [comment]
Just checked, works for me. Going to make them work out of the box.

**Comment by cybre** [comment]
While we're at it, we need new icons for OwnCloud. The current ones are just white Numix icons.

**Comment by RafaelCz** [comment]
I'll take a look at it ;)

**Comment by cybre** [comment]
That would be grand ;)

**Comment by RafaelCz** [comment]
![bildschirmfoto vom 2015-05-31 14 28 49](https://cloud.githubusercontent.com/assets/7204193/7902124/b00d2adc-07ac-11e5-813c-ba4a16c41ea0.png)
@cybre how about we use the cloud icons by @fsvh?
It makes more sense to use them for ownCloud instead of for Megasync.

**Comment by fsvh** [comment]
@RafaelCz I like it! =)

**Comment by RafaelCz** [comment]
great!

**Comment by fredrikekelund** [comment]
I'm using ownCloud version 2.0.2 and it seems I've ran into this again - I've turned on ownCloud in the elementary+ config panel, but the icon in Wingpanel remains the same.

**Comment by fredrikekelund** [comment]
The problem I was having seems to have resolved itself with the latest version of ownCloud
