### ISSUE TITLE
Extending elementaryPlus with beginner command-line scripts

### ISSUE THREAD

**Issue by orschiro** [mank319/elementaryPlus#142]
The Linux desktop provides many excellent programs that come with an easy-to-use graphical user interface (GUI), and an increasing number is meant for eOS. However, for many small tasks - for example to switch your laptop into standby after X minutes - the command line is often the de-facto interface (see [this](https://github.com/orschiro/eos-beginner-scripts/blob/master/scripts.sh) quick example). As a result, for many minor tasks there are no graphical software equivalents. Yet especially for new Linux users - I assume that particularly elementaryOS attracts many new Linux users - the command line is an unknown, thus awful interface to use.

My idea was to help and advocate those users by providing an easy to integrate script collection. Essentially it could be one Bash script containing a maintained selection of Bash aliases and functions that the user can enable and that is then automatically sourced upon start of the user session. I started [this repo](https://github.com/orschiro/eos-beginner-scripts) until I realised that such a collection would also nicely integrate into elementaryPlus and more properly merge the efforts we all take to advocate eOS and the Linux desktop. 

Thus, what do you think of such an integration? My thoughts were adding a switch to the installer that adds the alias and function collection to the local Bash shell of a user.

I look forward to your thoughts. 

Robert

**Comment by cybre** [comment]
elementary+ started as an icon theme and I think it should stay that. That's just my opinion.
@quassy @mank319 What do you guys think?

**Comment by quassy** [comment]
I agree with @cybre. For me elementary+ is for polishing the *elementary experience* as much as possible when you are using something that is not shipped by default. While the basic idea of a script collection has some merit it would be a completely different task (and I would not limit it to elementary).

**Comment by orschiro** [comment]
> While the basic idea of a script collection has some merit it would be a completely different task (and I would not necessarily limit it to elementary).

I see the argument. Is anyone of you aware of an initiative that aims for such an easy-to-use and integrate script collection aimed at particularly Linux beginners?
