### ISSUE TITLE
Icon request: Gnome System Monitor

### ISSUE THREAD

**Issue by cybre** [mank319/elementaryPlus#163]
Original icons (16x16 - 128x128):
![screenshot from 2015-06-07 13 08 10](https://cloud.githubusercontent.com/assets/3101505/8023678/44cd03d6-0d16-11e5-99dd-839708b777f8.png)

Icon names:
```
utilities-system-monitor
gnome-monitor
```

**Comment by RafaelCz** [comment]
I'm using these:
![preview](https://cloud.githubusercontent.com/assets/7204193/8025788/8698f5f8-0d62-11e5-9c7c-ae1762e10772.png)
You can find them [here](http://danrabbit.deviantart.com/art/elementary-Icons-65437279), they are licensed under GPL ;)

**Comment by RafaelCz** [comment]
@cybre I'm going to create the missing 16px version and make a pull request

**Comment by cybre** [comment]
@RafaelCz Great!
