### ISSUE TITLE
New Skype indicator icons needed!

### ISSUE THREAD

**Issue by cybre** [mank319/elementaryPlus#17]
The current ones render blurry since an update for Wingpanel has been issued which makes all the indicators 24x24 on Freya. It would be great if someone created new ones. You can use the ones in the repo (scripts/skype/icons/) for reference.
Guidelines: 
1. The icons should be monochrome (white for online status icons, some variation of blue for message notification icons) ! Other colours can be used for small, additional elements (i.e. the message count)
2. The canvas size must be 24x24 whereas the actual icon size must not be 16x16.
Additional elements (i.e. the message count) can exceed the 16x16 area.

**Comment by hendricha** [comment]
silly idea: just enlarge the drawing area and center the icons?

**Comment by cybre** [comment]
@hendricha The icon would look too small.

**Comment by mank319** [comment]
@hendricha will probably do as a workaround! I'd prefer an icon that is a bit too small to a blurred one.

**Comment by mank319** [comment]
@cybre have you tested it? Maybe it is not that well recognizable. At least as a temporary solution?

**Comment by cybre** [comment]
@mank319 It's good as a temporary solution but creating new ones would be better because the current ones have a gradient and shadows (which are not needed because wingpanel drops the shadows for us). I will have to add those guidelines to the bug report.

**Comment by murdej** [comment]
It may be something like this?
![skype](https://cloud.githubusercontent.com/assets/6561966/5797447/5c5329f0-9fba-11e4-9cf4-274d7ea8a51f.png)

**Comment by cybre** [comment]
The transparent elements should be a bit thinner. The message count is hard to read and I would like to see the icon with the count coloured in blue (makes it easier to see).

**Comment by murdej** [comment]
ok, can you send a link to another icon for inspiration?

**Comment by murdej** [comment]
variant two
![skype](https://cloud.githubusercontent.com/assets/6561966/5807561/d4db007c-a024-11e4-9082-7f4bdbfcc8fc.png)

**Comment by cybre** [comment]
I'm sorry, I've just realized these icons will be really small so the first variant (with the "fatter" transparent elements) actually looks better. Now when that's covered, we should think about making the message count more readable. Here are some more guidelines: The actual image size must be 24x24 whereas the actual icon size must be 18x18 as shown here:
![ff](https://cloud.githubusercontent.com/assets/3101505/5809220/9459d584-a036-11e4-8635-1c444aec1f35.png)
This stands for the base of the icon, additional elements like the message count can exceed the 18x18 area.

**Comment by bil-elmoussaoui** [comment]
if you are interested we can put a bounty on this ?? i would really get a better icons for this,dropbox, redshift and more ;)

**Comment by TraumaD91** [comment]
I believe they are trying to do icons in a 24x24 size with an actuall drawing area of 16x16 in Freya. Source: https://plus.google.com/105482608466099682215/posts/C38vft5ipuS

**Comment by RafaelCz** [comment]
Hey, 
I created a skype indicator iconset from scratch in Inkscape, which matches the look and feel of elementary OS. 
Instead of supertiny numbers, there is only a blue ball... the same as the one at the notification-indicator.

![skype-indicator](https://cloud.githubusercontent.com/assets/7204193/7171035/e722fabc-e3d3-11e4-8508-9c48a93b4da1.png)

I'm going to send a pull request to @mank319 ...as soon as I figured the whole GitHub-thingie out :)

**Comment by cybre** [comment]
Wow, those are great! If you're not sure about git, you can just send us
the icons and we'll do the git work and credit you in the project CREDITS
file.

**Comment by mank319** [comment]
@RafaelCz they look great indeed :+1:
As @cybre suggested you might as well just send them to us. On the other hand knowing your way around `git` might prove useful in the future, so it's definitely a desirable skill :wink:

**Comment by quassy** [comment]
Thanks again ;)

**Comment by Thyriaen** [comment]
they do not work with newest version of skype-beta ( https://www.skype.com/en/download-skype/skype-for-linux/downloading/?type=weblinux-deb ).

Nor does the dock icon
