### ISSUE TITLE
Cannot remove elementary+ configurator 

### ISSUE THREAD

**Issue by annleeli** [mank319/elementaryPlus#186]
I have removed and purged elementaryplus, but elementary+ configurator lingers and I can't get rid of it. Is there a specific package I'm not removing? What command should I run to uninstall the configurator? 

I have tried reinstalling elementary+ and purging. 

![elementaryplus](https://cloud.githubusercontent.com/assets/8731935/8221761/64a60faa-1530-11e5-88fc-7c825400f28d.png)

**Comment by quassy** [comment]
Does clicking on the icon in Slingshot actually do something or is that only a leftover shortcut? (Either way, it's a bug.)

If it is only an empty shortcut which does not do anything, you can check `~/.local/share/applications/` and `/usr/share/applications` if there is still a .desktop file for elementary+

**Comment by RafaelCz** [comment]
It's definitely a bug. There are several files left over, this should no happen.

@annleeli  
`sudo rm /usr/share/applications/elementaryPlus.desktop` and 
`sudo rm /usr/bin/elementaryplus-configurator` should delete the most.

@cybre according to [this documantation](https://wiki.debian.org/MaintainerScripts), these files should be removed by `postrm` during uninstall.
IMHO it would be even better to place all those files into the correct folder-structure inside the deb.

**Comment by cybre** [comment]
I've added `postrm`. We'll see if it works in the next build.
The folder structure inside the deb is already correct:
```
 cybre > ~/Downloads/elementaryplus_1.0+175+26-ubuntu14.04.1_all > tree -d -L 3
.
├── DEBIAN
└── usr
    └── share
        ├── doc
        ├── elementaryPlus
        └── icons
```

**Comment by RafaelCz** [comment]
but you could also add
```
/usr/bin/elementaryplus-configurator
/usr/share/applications/elementaryPlus.desktop
/usr/share/glib-2.0/schemas/apps.elementaryPlusConfigurator.gschema.xml
```
directly into the correct folders instead of fiddling around with `postinst`and `postrm`
In my opinion this would be the more elegant way...

**Comment by cybre** [comment]
@RafaelCz Didn't know `install` supported individual files. Updated now and waiting to build.

**Comment by RafaelCz** [comment]
How does this deb-building work? I don't see any `DEBIAN, doc, usr` or  `share` folder in this repo...
I guess a script is creating this folder-structure and moving the files into the their place, right?

**Comment by cybre** [comment]
The build recipe imports the `debian` folder from launchpad.
```
# bzr-builder format 0.3 deb-version {debupstream}+{revno}+{revno:packaging}
lp:elementary+
merge packaging lp:~cybre/elementary+/debian
```
The folder structure in the deb is created by the builder.

**Comment by cybre** [comment]
The newest revision in the debian packaging branch in launchpad fixes this issue.
It now copies the .desktop and the schema via the `install` file. The configurator is still copied with the `postinst` script and is now being removed via the `postrm` script.
Launchpad doesn't like us today, so the updated version may take some time to build.

**Comment by quassy** [comment]
Just tested it: The .desktop file and binary seem to be installed and removed just fine. Only thing that's off for me is that I have to reboot to make the icon appear in Slingshot (killing wingpanel does not help).

*elementary with unstable repos, up-to-date in VirtualBox*
