### ISSUE TITLE
Skype Icons

### ISSUE THREAD

**Issue by MDims** [mank319/elementaryPlus#200]
Skype Icons restored to default (colorful) icons after last system update (Date: 27/06/2015).

**Comment by cybre** [comment]
We've updated our patched sni-qt recently. You'll have to remove and install the Skype (or any other) icons again via the configurator. (I would suggest running 'rm -rf ~/.local/share/sni-qt/` before)

**Comment by MDims** [comment]
Oh, thank you very much, solved it.
