### ISSUE TITLE
Spotify icon not change (re: Issue #133)

### ISSUE THREAD

**Issue by sphaugh** [mank319/elementaryPlus#202]
I have tried following the instructions in #133 and the Spotify icon remains stock. Perhaps I have installed the wrong `spotify-client`? 

I also noted:
```
$ dpkg -l | grep sni
ii  sni-qt:amd64    0.2.6-0ubuntu1    amd64        indicator support for Qt
```
Do I need to install `sni-qt:i386`? 
```
The following packages have unmet dependencies:
 sni-qt:i386 : Depends: libqtgui4:i386 (>= 4:4.8.5+git192-g085f851+dfsg-2ubuntu4.1) but 4:4.8.5+git192-g085f851+dfsg-2ubuntu4+elementary3+r1~ubuntu0.3.1 is to be installed
```

**Comment by cybre** [comment]
How did you install the icon theme? From here or from the PPA?

**Comment by sphaugh** [comment]
From the PPA. After I restarted I tried using elementary+ Configurator to apply the Spotify icon, which didn't work. Afterwards I tried to apply the icon by running `install.sh`, which also didn't work. I made sure to `rm -rf /tmp/sni-qt_spotify_*` before both attempts.

As a note, I am successfully using `fix-spotify-icon` in the meantime.

**Comment by cybre** [comment]
`0.2.6-0ubuntu1`

This is not our patched sni-qt.
Make sure you have the [right PPA](https://launchpad.net/~cybre/+archive/ubuntu/elementaryplus) and update/upgrade your system.
```
sudo add-apt-repository ppa:cybre/elementaryplus
sudo apt-get update
sudo apt-get upgrade
```

The version should be `0.2.6-67~ubuntu14.04.1`.

**Comment by sphaugh** [comment]
Aha!
```
The following packages have been kept back:
  sni-qt
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```
I've removed the version on my system, how do I make sure that I'm installing the correct `sni-qt`?

**Comment by cybre** [comment]
sudo apt-get dist-upgrade

**Comment by sphaugh** [comment]
```
sph@gema:~$ sudo apt-get dist-upgrade
[sudo] password for sph: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
sph@gema:~$ dpkg -l | grep sni-qt
```

Is there a deb I can install directly?

**Comment by sphaugh** [comment]
I found the deb in #192, installed it and ran `apt-get -f dist-upgrade`.

```
sph@gema:~/Downloads$ dpkg -l | grep sni-qt
ii  sni-qt:amd64    0.2.6-67~ubuntu14.04.1    amd64        indicator support for Qt
```

I think `apt-get` is downloading the wrong `sni-qt` package.

**Comment by sphaugh** [comment]
I removed `spotify` and ran `apt-get install spotify-qt`. This resolved the issue.
