### ISSUE TITLE
Spotify tray icon

### ISSUE THREAD

**Issue by TicTac7x** [mank319/elementaryPlus#203]
Fix Spotify tray icon.

**Comment by quassy** [comment]
I guess you want to tell us, that the Spotify icon is not working for you? Do you have our patchted sni-qt version installed? 

If not, you can try this: 
    sudo add-apt-repository ppa:cybre/elementaryplus
    sudo apt-get update
    sudo apt-get upgrade

Also try (see issues #202):

> I removed `spotify` and ran `apt-get install spotify-qt`. This resolved the issue.

**Comment by TicTac7x** [comment]
Ohh okay, makes sense, worked.

**Comment by cybre** [comment]
I'll modify the patch later to fix these problems.

**Comment by TicTac7x** [comment]
You could actually improve it so that the user does not have to install the qt version. Look at this script, that worked perfectly: https://github.com/faviouz/fix-spotify-icon

**Comment by cybre** [comment]
That's even more hacky than the current implementation. I don't see it as an improvement.

**Comment by sphaugh** [comment]
Note that you may need to use `aptitude` or `synaptic` to download the dependencies for patch `sni-qt`. Initially my `apt-get` only suggested to remove or hold back the `sni-qt` package.

**Comment by cybre** [comment]
@sphaugh This has been hopefully fixed in the newest commit to the patched sni-qt (changed the versioning).

**Comment by TicTac7x** [comment]
Actually it's not that hacky, just replace the 512 png file in the zip file with yours and all done.

**Comment by sphaugh** [comment]
@cybre You might also change the error notification in [`elementaryPlus/blob/master/scripts/spotify/setup.sh`](https://github.com/mank319/elementaryPlus/blob/master/scripts/spotify/setup.sh) to ensure that `spotify-qt` is installed.
