### ISSUE TITLE
can't install patched sni-qt because of unmet dependencies 

### ISSUE THREAD

**Issue by RafaelCz** [mank319/elementaryPlus#204]
Several users at [elementary os stackexchange](http://elementaryos.stackexchange.com/questions/33/how-can-i-change-the-skype-icon-in-the-wingpanel-to-match-the-default-style/37#comment217_37) have problems to install the newest patched version of sni-qt. This is the error message they get:
```
sni-qt : Depends: libqtgui4 (>= 4:4.8.5+git192-g085f851+dfsg-2ubuntu4.1) but 4:4.8.5+git192-g085f851+dfsg-2ubuntu4+elementary3+r1~ubuntu0.3.1 is to be installed
```
@cybre Is there anything they can do to solve this problem?

**Comment by sphaugh** [comment]
I had the same problem. Try following instructions in #202 and #203. You may need to use `aptitude` or `synaptic` to select the dependencies for installation. Apparently the build recipe has been changed to fix these dependencies and I just updated to the new version with no trouble:
```
sph@gema:~$ dpkg -l | grep sni
ii  sni-qt:amd64    0.2.7-0~77~ubuntu14.04.1    amd64        indicator support for Qt
```

**Comment by codokkoli** [comment]
thanks, I was able to install it. 
But now I can't see the skype icon in the wingpanel anymore, any ideas what's the problem here?

**Comment by cybre** [comment]
There's a problem with some dependencies because of the elementary os
patches PPA. I'll investigate further and try to find a solution.

**Comment by quassy** [comment]
> thanks, I was able to install it.
But now I can't see the skype icon in the wingpanel anymore, any ideas what's the problem here?

Have you tried flipping the switch for Skype in elementary+ Configurator twice and closing and restarting Skype?

**Comment by cybre** [comment]
The amd64 build installs correctly but the i386 build has some problems
with dependencies.

**Comment by codokkoli** [comment]
> Have you tried flipping the switch for Skype in elementary+ Configurator twice and closing and 
> restarting Skype?

Yes I've tried that a couple of times. My best guess is that I broke something while trying to install the right sni-qt version yesterday.

**Comment by cybre** [comment]
This has been fixed in the last update. Please report.

**Comment by codokkoli** [comment]
Works like a charm now, thank you!
