### ISSUE TITLE
Trying to install spotify indicator gives this error

### ISSUE THREAD

**Issue by harshi3t** [mank319/elementaryPlus#207]
spotify was toggled ON
To install:  ['spotify']
To remove:  []
Installing patched sni-qt
Traceback (most recent call last):
  File "./scripts/elementaryplus-installer.py", line 423, in install
    if subprocess.call(['pkexec', scripts + "sni-qt.sh"]) == 0:
NameError: global name 'subprocess' is not defined

**Comment by harshi3t** [comment]
Sorry, This error was encountered when trying through terminal (install.sh).
The install happened smoothly when I tried straight through elementary+ Configurator app.
So, feel free to close this issue.

**Comment by cybre** [comment]
It is a bug, I'll fix it in a moment.
