### ISSUE TITLE
Sni-qt source code

### ISSUE THREAD

**Issue by bil-elmoussaoui** [mank319/elementaryPlus#210]
Hello, 
I'm looking for the source code of the patched version of sni-qt that you provide in your ppa to use it in my Hardcode-Tray fixer script. I would use your official ppa but you only provide Ubuntu Trusty version; there's no support for Ubuntu 15.04..

Thank you

**Comment by cybre** [comment]
I have already planned to expand the build target list. Consider it done :)

**Comment by cybre** [comment]
There! https://launchpad.net/~cybre/+archive/ubuntu/sni-qt-eplus

**Comment by bil-elmoussaoui** [comment]
Thank you! if you can add 14.10 as well? :+1:

**Comment by cybre** [comment]
Sure. Didn't think anyone used that :)

**Comment by bil-elmoussaoui** [comment]
I use it on my script [HardcodeTray-Fixer](https://github.com/bil-elmoussaoui/Hardcode-Tray) Thank you very much!!
