### ISSUE TITLE
Owncloud icons

### ISSUE THREAD

**Issue by bil-elmoussaoui** [mank319/elementaryPlus#215]
Hello, 
I've been trying to use elementaryPlus Configurator to change ownCloud indicator icons. The icons are installed in ```.local/share/sni-qt/icons/owncloud```
But the icons are not working.. i guess the icons name are not correct. I used them in my script HardcodeTray-Fixer and still have the same result 
@RafaelCz what do you think about this? 
I'm using the latest version of elementaryPlus & sni-qt 
Thank you!

**Comment by RafaelCz** [comment]
What's your exact version of sni-qt? Please, run
```
dpkg -l | grep sni-qt
```
and paste your output here.

**Comment by bil-elmoussaoui** [comment]
```
ii  sni-qt:amd64                                0.2.7-0~78~ubuntu14.04.1                                  amd64        indicator support for Qt
ii  sni-qt:i386                                 0.2.7-0~78~ubuntu14.04.1                                  i386         indicator support for Qt
```

**Comment by cybre** [comment]
Owncloud version?

**Comment by bil-elmoussaoui** [comment]
I'm using 1.5, i don't think it's the latest version?

**Comment by cybre** [comment]
No, your version is really behind. The latest version is 1.8.3

**Comment by RafaelCz** [comment]
no, the latest version is 1.8...
@cybre I guess elemantary+ should provide icons for both versions, since owncloud 1.5 is default in ubuntu repo and not everybody is adding other PPAs

**Comment by cybre** [comment]
@RafaelCz I agree! @bil-elmoussaoui Can you send us the icon names? (There are 6 of them)

**Comment by bil-elmoussaoui** [comment]
Where i can find those files?

**Comment by cybre** [comment]
They are located at /tmp/sni-qt_owncloud_*****-******/

**Comment by bil-elmoussaoui** [comment]
I've only one, as i don't really use owncloud the icon is
```owncloud_4495_9aa8a4ac4a70ca6c739c4de13dfbfedb.png```
sorry about that :/

**Comment by bil-elmoussaoui** [comment]
Just one more question , if an icon for example x_y_z.png in /tmp/, this icon can be copied in to /.local/share/icons/x/z.png ?

**Comment by cybre** [comment]
Yes

**Comment by bil-elmoussaoui** [comment]
Thanks for the informations :+1:
