### ISSUE TITLE
elementary tweak should not be used anymore 

### ISSUE THREAD

**Issue by RafaelCz** [mank319/elementaryPlus#225]
It's not recommended to use elementary tweaks as it is [no longer maintained](https://plus.google.com/u/0/+MichaelStarkweather/posts/Y8zixFDEWiv) and has been known to break systems.
IMHO elementary+ shouldn't mention it in it's installation guide... what do you think?

**Comment by quassy** [comment]
In general I agree. Even more so because the new installer can change the theme (and revert back to the original one) itself, so manually using elementary Tweaks or gsettings set is not needed anymore. 

> has been known to break systems

Is it?

**Comment by cybre** [comment]
@quassy The installer can't change the theme when installed from the PPA.
I say we just provide a gsettings set for elementary+ and another one for reverting back to elementary.

And yes, I removed the Dropbox script because it didn't work.

**Comment by quassy** [comment]
> The installer can't change the theme when installed from the PPA.

Why is that? Can't the installer call `subprocess.call("gsettings set org.gnome.desktop.interface gtk-theme elementaryPlus")`?

**Comment by cybre** [comment]
Well, yes (and no, I would use the Gio.gsettings module),
The "Core Icon Theme" entry doesn't appear in the version installed from the PPA because
the installer is for installing and removing things only atm (wouldn't be smart to remove the theme when it's owned by our Debian package).
I guess I could add a button instead of a switch for toggling the theme or just make the switch toggle the theme when installed from the PPA (I feel the latter would be confusing as one would expect it to remove the core icon theme).
What do you think?

**Comment by RafaelCz** [comment]
In my opinion adding another button is not the solution, it will probably cause more confusion.

A typical user (I'm not talking about a tech-savvy user) doesn't care if he is installing or enabling something by toggling a switch, he wants to see that something changes, he wants to see a reaction.

The most confusing part about the elementary+ Configurator is:
*Why is this Skype switch on? My damn Skype icon is still butt ugly... ohhh right, I remember now, I've deleted the icons by hand a few days ago.*

The Configurator shouldn't set the toggles by a saved "installed" status, it should check for existence of the files (or symbolic links), like it does for the applications. The user could have deleted some of the files on purpose or by accident. 
The "Core Icon Theme" should also always be visible and, in case it is set as default icon theme, toggled on. If it is not set as default, and the user toggles the switch, there are two possibilities
**elementary+ from the PPA:**
save current default icon-theme
set "elementaryPlus" as default icon-theme

**elementary+ from GitHub**
save current default icon-theme
Check for existence of `/usr/share/icons/elementaryPlus` or `~/.icons/elementaryPlus`
if it doesn't exist, copy the theme to `~/.icons/`
set "elementaryPlus" as default icon-theme

The user won't care, if he just installed or enabled this icon-theme.

**Comment by quassy** [comment]
Does the installer actually check if elementary icon theme is installed as well?

**Comment by cybre** [comment]
The elementary+ Configurator started as a simple tool. It evolved (didn't really expect for this to happen). All the points you've made were on my mind for quite some time, I just didn't have the time to address all these issues (school, other stuff). Now I have all the time of the world and I plan to spend some of it on changing how the installer works. I've already started making some changes (migrating all the bash scripts to python).

**Comment by cybre** [comment]
I'm going to drop the "Apply" button and replace the switches with buttons ("Enable" and "Disable", none of the "Remove", "Install" nonsense). It's going to take some time (I'm quite the procrastinator), but not too much (this weekend, maybe next week).
