### ISSUE TITLE
Icon request: Bitcoin core (indicator)

### ISSUE THREAD

**Issue by timdev21** [mank319/elementaryPlus#226]
Would be nice to have a black and white icon for the wingpanel

**Comment by RafaelCz** [comment]
![bitcoin-indicator](https://cloud.githubusercontent.com/assets/7204193/8559900/ac591792-2512-11e5-94cc-c0cbb99dd7c3.png)
![bitcoin](https://cloud.githubusercontent.com/assets/7204193/8559901/add06e86-2512-11e5-844c-d54b23d8f872.png)

**Comment by codokkoli** [comment]
nice, I like them!

**Comment by netforhack** [comment]
@RafaelCz dont work in ubuntu 14.04,  try to resize to 22x22, but its not helpd
