### ISSUE TITLE
Icon request: XChat

### ISSUE THREAD

**Issue by quassy** [mank319/elementaryPlus#237]
Icon name: `xchat`
Official icon: 
![xchatlogo2](https://cloud.githubusercontent.com/assets/369996/8584503/73f9e6cc-25d7-11e5-9fe8-e9df69f282e8.png)

**Comment by cybre** [comment]
The icon name is `xchat`

**Comment by bil-elmoussaoui** [comment]
[elementary extras icons]( http://spg76.deviantart.com/art/elementary-extras-Icons-215459969)
