### ISSUE TITLE
Icon request: HexChat

### ISSUE THREAD

**Issue by cybre** [mank319/elementaryPlus#239]
Icon name: hexchat
Original icon:
![hexchat](https://cloud.githubusercontent.com/assets/3101505/8584787/b5e7f6c0-25da-11e5-9ad9-aa7796dd3de1.png)

**Comment by elmat0** [comment]
How's this?
![hexchat](https://rawgit.com/elmat0/icons_etc/b5e966fdf5e9ac58116094057e59708b92562c38/apps/128/hexchat.svg)

**Comment by cybre** [comment]
:+1:
