### ISSUE TITLE
Icon request: MEGASync

### ISSUE THREAD

**Issue by cybre** [mank319/elementaryPlus#240]
Icon name: mega
Original icon:
![mega](https://cloud.githubusercontent.com/assets/3101505/8584812/f41fc92c-25da-11e5-9f68-4f7e6cf43bb7.png)

**Comment by TraumaD** [comment]
Preview of the icon I just submitted for PR:
![mega](https://cloud.githubusercontent.com/assets/10608836/14407245/69332b16-fe87-11e5-89c6-3ef05c239379.png)
