### ISSUE TITLE
Icon request: FileZilla

### ISSUE THREAD

**Issue by cybre** [mank319/elementaryPlus#241]
Icon name: filezilla
Original icon:
![filezilla](https://cloud.githubusercontent.com/assets/3101505/8584828/2542b2f8-25db-11e5-9b67-1231884affe5.png)

**Comment by bil-elmoussaoui** [comment]
there's already an icon here : [elementary extras icons]( http://spg76.deviantart.com/art/elementary-extras-Icons-215459969)

**Comment by RafaelCz** [comment]
I'm going to add spg76's icon, it's released under GPL.

**Comment by quassy** [comment]
Regarding elementary extras: The FileZilla icon looks good, some other seem to be dated and more like Tango though, so we have took check each and every icon.

**Comment by RafaelCz** [comment]
Indeed... I'd suggest to add deja-dup & audacity aswell

**Comment by RafaelCz** [comment]
and Liferea & Rhythmbox
