### ISSUE TITLE
Icon request: OwnCloud

### ISSUE THREAD

**Issue by cybre** [mank319/elementaryPlus#243]
Icon name: owncloud
Original icon:
![owncloud](https://cloud.githubusercontent.com/assets/3101505/8584840/496df3a4-25db-11e5-9846-8e62b2ab212a.png)

**Comment by peteruithoven** [comment]
The OwnCloud client has an "Use Monochrome Icons" option in it's settings, which is a great step forward, although it's not HiDPI. 
![screenshot from 2017-06-05 02 01 08](https://cloud.githubusercontent.com/assets/523210/26766472/deacfc26-4992-11e7-90a4-e4a9b8d74cdf.png)

**Comment by peteruithoven** [comment]
Owncloud's client's HiDPI issue seems to be resolved: https://github.com/owncloud/client/issues/11 (not sure why since I still see a blurry icon)
