### ISSUE TITLE
Icon request: Skype

### ISSUE THREAD

**Issue by cybre** [mank319/elementaryPlus#259]
Icon name: skype
Original icon:
![skype](https://cloud.githubusercontent.com/assets/3101505/8611865/e7ba8ca6-26c7-11e5-80df-848555405189.png)

**Comment by harshi3t** [comment]
I think this is a good candidate.

![](http://img01.deviantart.net/e73f/i/2011/236/a/2/eskype_by_mastropino-d3dhgu2.png)

http://mastropino.deviantart.com/art/eSkype-204048506

**Comment by quassy** [comment]
We can only use it if we get permission from the author / he uses a proper OpenSource licence.

**Comment by harshi3t** [comment]
Hope you get permission to use it as I've seen this icon included in other elementary icon packs.

**Comment by cybre** [comment]
The gradient could a bit softer :)

**Comment by RafaelCz** [comment]
I'm also not really fond of this icon... it seems to follow an older version of elementary OS HIG
I've been trying to recreate a skype icon from scratch, which one do you prefer?

sunken "S"
![skype](https://cloud.githubusercontent.com/assets/7204193/8635330/b3ab0276-281e-11e5-891e-725df0baa766.png)

or raised "S"
![skype2](https://cloud.githubusercontent.com/assets/7204193/8635332/c85cea54-281e-11e5-9d98-76bf757cdf6b.png)

**Comment by cybre** [comment]
Raised.

**Comment by quassy** [comment]
Raised.

**Comment by timdev21** [comment]
yep, the raised one is better

**Comment by mathias-github** [comment]
Any progress on this one?

**Comment by elmat0** [comment]
Included in [this](https://github.com/mank319/elementaryPlus/issues/220) batch.

**Comment by quassy** [comment]
I think the lighting should be a bit more subtle, but apart from that it looks fine.
