### ISSUE TITLE
elementary+ Configurator not present in Slingshot immediately after installing/updating

### ISSUE THREAD

**Issue by harshi3t** [mank319/elementaryPlus#265]
It appears only after restarting slingshot-launcher.

**Comment by RafaelCz** [comment]
@cybre perhaps adding `update-desktop-database -q` to the postinst script might solve the issue.

**Comment by cybre** [comment]
@RafaelCz Done, now we wait :)

**Comment by cybre** [comment]
Nope, that didn't work.

**Comment by cybre** [comment]
I give up. I don't know what the problem is. The launcher shows up in search but not in the overview.

**Comment by cybre** [comment]
This has been hopefully fixed in the latest version. Can you confirm?

**Comment by harshi3t** [comment]
Can confirm. It's fixed :+1:
