### ISSUE TITLE
Support HiDPI

### ISSUE THREAD

**Issue by quassy** [mank319/elementaryPlus#269]
We should follow the official elementary icon theme and support HiDPI. All this requires (in theory) is a [couple of symlinks and changes to index.theme](http://blog.elementary.io/post/124193007916/whats-up-with-hidpi-icons). (It'd good if someone could test HiDPI on actual hardware.)

**Comment by cybre** [comment]
I'll do it. 
I can't test it, though.

**Comment by quassy** [comment]
Cool! Any idea on how to make the sni_qt indicators HiDPI?

**Comment by cybre** [comment]
Nope. I don't think it's possible because PNG (also because sni-qt is a peace of s**t software)

**Comment by RafaelCz** [comment]
I saved every sni-qt indicator icon, that I've created, as SVG. I could easily export double sized PNGs.

**Comment by quassy** [comment]
Do we know for sure sni-qt does not support SVG in some way?

**Comment by cybre** [comment]
It supports SVG, but converts in to a large PNG (1772x1772)! I'll need to make some tests to see if we're loosing quality with the downscaling (to 24x24).

**Comment by cybre** [comment]
Scaling factor: 2

&nbsp;&nbsp;PNG  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; SVG
![scale2](https://cloud.githubusercontent.com/assets/3101505/8851091/6c9a23ca-314d-11e5-95d7-600039b0b6a8.png)

Scaling factor: 1

PNG&nbsp;&nbsp;SVG
![scale1](https://cloud.githubusercontent.com/assets/3101505/8851121/aaab9a4a-314d-11e5-9326-ad7ea0770fa7.png)

The PNGs are 24x24, and the SVGs are 256x256 (which then sni-qt exports to a 256x256 PNG)

**Comment by quassy** [comment]
Could we just make the SVGs 48px? I'd guess memory usage goes up if all indicator icons are downscaled 256px originally.

**Comment by cybre** [comment]
I can't see why we couldn't :)

**Comment by bil-elmoussaoui** [comment]
Just to be sure that i do understand everything, the svg icons does not need to be converted to png icons for Qt indicators ?

**Comment by quassy** [comment]
As I understand it no, sni-qt apparently can do this itself (and does it quite badly).

**Comment by cybre** [comment]
@bil-elmoussaoui You won't need to convert to PNG after I release the new patch!
