### ISSUE TITLE
Team Fortress 2 low res default icon

### ISSUE THREAD

**Issue by Polochamps** [mank319/elementaryPlus#28]
Hi,

I'm having an icon issue on this particular game as it doesn't use the tf2 icon by TraumaD91.
It just uses the default low res icon after launching the game and alt tabbing it.

Thank you

**Comment by quassy** [comment]
Can you check if this is still relevant with an updated version of elementary+? I believe this should have been fixed by [fb945ada068847cd10f0939eb91c7c2459e27dfd](https://github.com/mank319/elementaryPlus/commit/fb945ada068847cd10f0939eb91c7c2459e27dfd)

**Comment by quassy** [comment]
Closing as there was no reaction. If someone else still has this problem feel free to reopen this issue! :)
