### ISSUE TITLE
Icon request: ScudCloud (indicator)

### ISSUE THREAD

**Issue by t3mux** [mank319/elementaryPlus#283]

**Comment by RafaelCz** [comment]
elementary+ already provides a scudCloud indicator icon.

**Comment by quassy** [comment]
[panel](https://github.com/mank319/elementaryPlus/blob/master/elementaryPlus/status/24/scudcloud-panel.svg), [attention](https://github.com/mank319/elementaryPlus/blob/master/elementaryPlus/status/24/scudcloud-attention.svg)

**Comment by cybre** [comment]
Oh, I didn't know we already had it.
