### ISSUE TITLE
Icon Request: Openshot

### ISSUE THREAD

**Issue by mathias-github** [mank319/elementaryPlus#292]
Icon Name: openshot
Original Icon: 
![openshot_icon](https://cloud.githubusercontent.com/assets/8754153/9252594/d5c6b3d2-41e1-11e5-94da-bbd8fbe8a117.png)

**Comment by elmat0** [comment]
How's [this?](https://github.com/elmat0/icons_etc/blob/3663756e80397c91b77147e285e83bb719cb0740/apps/128/openshot.svg)

**Comment by mathias-github** [comment]
That looks great! :D

**Comment by mathias-github** [comment]
I personally liked the version with more gradient the most. https://github.com/elmat0/icons_etc/blob/3663756e80397c91b77147e285e83bb719cb0740/apps/128/openshot.svg

**Comment by elmat0** [comment]
I was swayed by the reference icons from [this](https://github.com/mank319/elementaryPlus/issues/27) post and did notice the gradient. I figured that was fair enough as the HIG mentions not to make items too reflective. I didn't notice the edges though. You have very good eyes. ;p

I agree the older one looked better. I'll revert them back.

**Comment by mathias-github** [comment]
Thanks!

**Comment by quassy** [comment]
Looking forward to the PR :)
