### ISSUE TITLE
Icon Request: TimeShift (missing 16 and 24 px)

### ISSUE THREAD

**Issue by png2378** [mank319/elementaryPlus#294]
Icon Name: timeshift

Icon: ![](http://i.imgur.com/MdEjkV8.png)

[More Info](http://www.teejeetech.in/p/timeshift.html)

**Comment by elmat0** [comment]
Here's a couple of options. Let me know which you prefer or suggest some improvements.

[Red square](https://github.com/elmat0/elementaryPlus/blob/master/elementaryPlus/apps/128/timeshift.svg), [Spinning clock](https://github.com/elmat0/elementaryPlus/blob/master/elementaryPlus/apps/128/timeshift_2.svg).

**Comment by png2378** [comment]
"Red square" is beautiful!

**Comment by theharryx** [comment]
Hello,
 it happens if had a try on that one on my own. Let me know if you like it
Icon:
![timeshift](https://cloud.githubusercontent.com/assets/14301077/9889268/ed63e7e4-5bf9-11e5-8d28-badcbe64f465.png)

**Comment by elmat0** [comment]
It's certainly a lot more creative than mine. :)

If I had to be picky I'd say you might have trouble with the detail at smaller scales and it's perhaps a little too glossy in comparison with the other icons. How did you manage to pull this off as a vector image?

**Comment by quassy** [comment]
Just merged #302 which includes the red square icon by @elmat0 in 32 to 128 px. 

Leaving this open as I hope 16 px and 24 px will follow :)

**Comment by elmat0** [comment]
Sorry I got a bit sidetracked with Minecraft. Do you know if the OS definitely uses those small sizes? I noticed a lot of the apps included already don't contain these icon sizes and was actually going to lodge a bug report, then I saw that the HIG only mentions 32 and up for apps.
