### ISSUE TITLE
Transmission monochrome appindicator not showing

### ISSUE THREAD

**Issue by anubeon** [mank319/elementaryPlus#295]
For some reason elementary plus' monochrome app
indicator icon isn't overriding  the default full colour icon for me.

![screenshot from 2015-08-24 10 34 06](https://cloud.githubusercontent.com/assets/1479629/9437146/6d810066-4a4c-11e5-8b14-46b88ecdd7ed.png)

I'm running latest elementary-daily packages on top of trusty. Let me know if you need any more details.

**Comment by bil-elmoussaoui** [comment]
Let me guess, you re using the gtk3 version of transmission ?

**Comment by anubeon** [comment]
I'm not sure; is there any way to find out.

If it helps, it's version 2.84 (14307).

**Comment by bil-elmoussaoui** [comment]
Just share a screenshot of the application

**Comment by anubeon** [comment]
![screenshot from 2015-08-24 11 53 06](https://cloud.githubusercontent.com/assets/1479629/9438578/d893f408-4a56-11e5-9850-d7b8d8de1636.png)

**Comment by RafaelCz** [comment]
@anubeon rename `transmission-panel.svg` to `transmission.svg`, it should do the trick...

**Comment by anubeon** [comment]
I added a soft link linking ../status/24/transmission-tray-icon.svg to  ../status/24/transmission-panel.svg (there was no transmission-panel.svg in place). That seems to have done the trick.

P.S. Out of interest, am I using the gtk3 version of transmission.

**Comment by RafaelCz** [comment]
OK, it seems like in version 2.84 the icons got renamed.
@anubeon no, you are not using the unofficial GTK3+ version of Transmission.
