### ISSUE TITLE
icon request: texmaker

### ISSUE THREAD

**Issue by belmakier** [mank319/elementaryPlus#31]
this one: http://www.xm1math.net/texmaker/

**Comment by elmat0** [comment]
Couple of options. Not totally convinced on the colour yet. Thoughts?
![circle](https://rawgit.com/elmat0/icons_etc/94da503262f128ade229a7ec1c9fcce3b87d4320/apps/128/texmaker.svg) ![cog](https://rawgit.com/elmat0/icons_etc/94da503262f128ade229a7ec1c9fcce3b87d4320/apps/128/texmaker2.svg)

**Comment by belmakier** [comment]
nice!  I like the right one a little more I think - slightly simpler.  
colour seems fine to me, the same as on their usual logo which is good.

**Comment by quassy** [comment]
Prefer the right one as well (also the gear on the left looks blurry). Yet another not-standard-shape icon! :+1:
