### ISSUE TITLE
Icon request: Code::Blocks IDE

### ISSUE THREAD

**Issue by tombuben** [mank319/elementaryPlus#310]
Icon name: codeblocks
Original icon:
![codeblocks](https://cloud.githubusercontent.com/assets/2141107/10375553/7634fb1a-6df9-11e5-9d5e-a39dec83bda7.png)

**Comment by elmat0** [comment]
How about [this?](https://github.com/elmat0/icons_etc/blob/master/apps/128/codeblocks.svg)

**Comment by quassy** [comment]
I like it. :+1:
