### ISSUE TITLE
Use Dota 2 icon

### ISSUE THREAD

**Issue by Gocht** [mank319/elementaryPlus#317]
I have seen an nice icon for Dota 2 game in Elementary+ icon's folder, but in my dock Dota 2 use the steam's icon, I can't find the option to use Elementary+ icon, How can I fix this?

**Comment by cybre** [comment]
You'll have to edit the desktop launcher manually to replace the icon. The launcher should be in `/home/<user>/.local/share/applications`. Just replace `Icon=steam` with `Icon=dota2`.

**Comment by Gocht** [comment]
Wow, so sweet! Thanks ! that fixed it.
