### ISSUE TITLE
Icon Request: TeamViewer

### ISSUE THREAD

**Issue by rootsandculture** [mank319/elementaryPlus#318]
Is there any chance to replace that ugly icon? As far I know Teamviewer  runs under wine, so don't know how to fix it.

https://dl.dropboxusercontent.com/u/69141415/Screenshot%20from%202015-11-13%2014%3A24%3A25.png

Here is a proper elementarized icon:
http://www.iconarchive.com/show/elementary-icons-by-danrabbit/Apps-teamviewer-icon.html

**Comment by rootsandculture** [comment]
No one?

**Comment by quassy** [comment]
The icon by Dan looks good / much better than the stock one, so I would not mind adding it. But we would need the icon in SVG format (in 128, 64, 48, 32, 24 and 16 px).

**Comment by rootsandculture** [comment]
Here's another one in .svg
http://www.icons101.com/icon/id_54184/setid_2043/Flatwoken_by_Alessandro_Roncone/teamviewer

**Comment by rootsandculture** [comment]
Seems final Teamviewer 11 version includes an icon notificator at the top panel, is there a fix for that, how can I manually replace that icon?
https://db.tt/6xdqT17W﻿

**Comment by cybre** [comment]
@rootsandculture Please open a new issue for the indicator icon.
