### ISSUE TITLE
qbittorrent icon request

### ISSUE THREAD

**Issue by Milozzy** [mank319/elementaryPlus#321]
Icon name: qbittorrent
Original icon: 
![2131270](https://cloud.githubusercontent.com/assets/864646/11445573/9fc89a80-952d-11e5-97d9-a1074d4e0d26.png)

Thanks!

**Comment by elmat0** [comment]
How's [this?](https://github.com/elmat0/icons_etc/blob/master/apps/128/qbittorent.svg)

I don't know if it's just me but 9/10 icons these days seem to be blue circles.

**Comment by quassy** [comment]
Could you make the "qb" raised? (Basically shadow below and outside instead of inside the letters.)

**Comment by elmat0** [comment]
Sure. How's [this?](https://github.com/elmat0/icons_etc/blob/master/apps/128/qbittorent.svg) I reduced the glare a bit too.

**Comment by quassy** [comment]
I like that one much better (and would merge it if no one objects).

**Comment by cybre** [comment]
Looks great!
