### ISSUE TITLE
Netflix Chrome webapp icon

### ISSUE THREAD

**Issue by Milozzy** [mank319/elementaryPlus#322]
Hi, can you please symlink the already existing Netflix icon to provide Chrome webapp support?

Icon name = chrome-deceagebecbceejblnlcjooeohmmeldh-Default

Thanks

**Comment by quassy** [comment]
Thanks @cybre, I wasn't able to symlink it myself because I'm still stuck on Windows :/. 

Could you also add symlinks for other Chrome profiles, in the form of `chrome-deceagebecbceejblnlcjooeohmmeldh-Profile_1.svg` (to 5)?

**Comment by cybre** [comment]
@quassy Sure.
