### ISSUE TITLE
Tomahawk indicator icon does not work.

### ISSUE THREAD

**Issue by jjeroennl** [mank319/elementaryPlus#330]
The tomahawk indicator icon as described in [here](https://github.com/mank319/elementaryPlus/pull/170) does not work on both my machine and on the machine of John Pirial on [Google +](https://plus.google.com/109103177896883454898/posts/LQJbPJVfMng).

Any debug info you might need you can ask me :) but I'm not at my PC right now so I can't include it.

**Comment by bil-elmoussaoui** [comment]
Which version of Tomahawk you're using ? And can you confirm that this file `usr/bin/tomahawk` do exists in your system?

**Comment by jjeroennl** [comment]
I'm using Tomahawk 0.8.4.
/usr/bin/tomahawk does exists, however I did check the Tomahawk icon in the elementary+ configurator.

![screenshot from 2015-12-17 21 10 58](https://cloud.githubusercontent.com/assets/8996200/11880725/c6198548-a502-11e5-85fe-07c7bafd7017.png)
![screenshot from 2015-12-17 21 11 30](https://cloud.githubusercontent.com/assets/8996200/11880730/cf50322e-a502-11e5-9671-a293abdbefc2.png)

Tomahawk traceback:
```
jeroen@CMstorm:/usr/bin$ tomahawk
Gtk-Message: Failed to load module "pantheon-filechooser-module"

(tomahawk:2949): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(tomahawk:2949): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(tomahawk:2949): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(tomahawk:2949): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(tomahawk:2949): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
Gtk-Message: Failed to load module "canberra-gtk-module"
Translation: Tomahawk: Using system locale: "en_US" 
Translation: Qt: Using default locale, system locale one not found: "en_US" 
TomahawkApp thread: QThread(0x24d4470) 

```

**Comment by bil-elmoussaoui** [comment]
Can you see if you have any tomahawk folder/icons in `$HOME/.local/share/sni-qt/`?

**Comment by jjeroennl** [comment]
I don't have any icons there. 
```bash: cd: /home/jeroen/.local/share/sni-qt/: No such file or directory```

**Comment by bil-elmoussaoui** [comment]
What's the output of `dpkg -l | grep sni-qt`?

**Comment by jjeroennl** [comment]
```bash
jeroen@Jeroen-PC:~$ dpkg -l | grep sni-qt
ii  sni-qt:amd64                                                0.2.8-0~79~ubuntu14.04.1    
                                    amd64        indicator support for Qt
```

**Comment by bil-elmoussaoui** [comment]
you need ti nstall the sni-qt:i386 version too! and copy the icons from here https://github.com/mank319/elementaryPlus/tree/master/scripts/icons/tomahawk to `.local/share/sni-qt/icons/tomahawk`

**Comment by jjeroennl** [comment]
That worked!
