### ISSUE TITLE
Create a icon for foxit reader

### ISSUE THREAD

**Issue by sandeepbhardwaj** [mank319/elementaryPlus#332]
Default icon for foxit reader is 
![foxitreader](https://cloud.githubusercontent.com/assets/11556149/12108228/50832472-b39b-11e5-8cb7-0a5abbaa0e78.png)
But it's not look good with other icons.

Icon name required for new icon :- FoxitReader

**Comment by elmat0** [comment]
How about [this?](https://github.com/elmat0/icons_etc/blob/master/apps/128/FoxitReader.svg)

**Comment by sandeepbhardwaj** [comment]
Beautiful. You are too good in your job. Thanks a lot.

**Comment by cybre** [comment]
Closed in #338
