### ISSUE TITLE
Teamviewer 11 Indicator Icon

### ISSUE THREAD

**Issue by rootsandculture** [mank319/elementaryPlus#335]
Seems final Teamviewer 11 version includes an indicator icon at the top panel, is there a fix for that? Can I manually replace that icon?
https://dl.dropboxusercontent.com/u/69141415/Screenshot%20from%202015-12-03%2012%3A42%3A37.png

Thanks

**Comment by bil-elmoussaoui** [comment]
The icons are 
```
0b040b0d9ec00ce0d8189ece93cd2b7f.png -> teamviewer-indicator
54b99333baa6a26fda3eb8ce6d664bd5.png -> teamviewer-indicator-error
4327113cab136a09fac832e66878159a.png -> teamviewer-indicator-connected
c28d37df9872311f7c6b295b70b8a39d.png -> teamviewer-indicator-away
86e4f5bf63a6fa1725afd2e08e0ce105.png -> teamviewer-indicator-offline
4cd9545d0021db224685d863ac738f91.png -> teamviewer-indicator-busy
```
we had an issue with fixing that in Hardcode-tray. Teamviewer ships an other version of sni-qt, you will need to replace it with the patched one 
`/usr/lib/i386-linux-gnu/qt4/plugins/systemtrayicon/libsni-qt.so -> tv_bin/RTlib/plugins/systemtrayicon/libsni-qt.so`

**Comment by cybre** [comment]
@bil-elmoussaoui Thanks! I'll get that into the configurator as soon as someone makes the icons!

**Comment by rootsandculture** [comment]
Hi guys, are the indicator icons updated in the latest ElementaryPlus update? today that package has been updated but the indicator icon doesn't change.

**Comment by cybre** [comment]
@rootsandculture The pull request hasn't been merged yet.

**Comment by cybre** [comment]
Closed in #341 and #345

**Comment by rootsandculture** [comment]
It doesn't work :( 
https://db.tt/wMSiNjJ0

**Comment by cybre** [comment]
Have you restarted teamviewer after enabling the configurator entry?

**Comment by cybre** [comment]
Also, please post the output of `dpkg --list sni-qt`.

**Comment by rootsandculture** [comment]
Yes, I restarted eOS. 
My output: http://pastebin.com/g1it6QgL

**Comment by cybre** [comment]
1. `sudo apt-get install sni-qt:i386`
2. Disable "TeamViewer" in the configurator.
3. Enable it again.

**Comment by rootsandculture** [comment]
Yes! It works now!

**Comment by rootsandculture** [comment]
One more question, is there an option or tweak for reorder the notification icons?

**Comment by cybre** [comment]
@rootsandculture As far as I know, there isn't.

**Comment by quassy** [comment]
@cybre Could the elementary+ Configurator check itself if appropriate versions of sni-qt are installed (patched; 64 and 32 bit)?

**Comment by cybre** [comment]
@quassy yeah, I plan on adding that functionality in the rewrite.

**Comment by rootsandculture** [comment]
I'm testing Loki Beta 2, and seems the indicator icon doesn't work.
