### ISSUE TITLE
libreoffice 5 icons are missing while installing using .deb

### ISSUE THREAD

**Issue by sandeepbhardwaj** [mank319/elementaryPlus#336]
Install libreoffice 5 with deb package then it's not picking the elementary plus icons. I have also verified in usr/share/applications location there is no .desktop file for libreoffice created in this case.

Note:- when installing libreoffice using ppa its picking the icons.

**Comment by elmat0** [comment]
Is there a .desktop file in `~/.local/share/applications/` instead?

**Comment by sandeepbhardwaj** [comment]
No,  there is no ```.desktop``` file for libreOffice inside ```~/.local/share/applications/```

**Comment by sandeepbhardwaj** [comment]
No, there is no ```.desktop``` file for libreOffice inside ```~/.local/share/applications/```

**Comment by sandeepbhardwaj** [comment]
No, there is no ```.desktop``` file for libreOffice inside ```~/.local/share/applications/```

**Comment by bil-elmoussaoui** [comment]
@sandeepbhardwaj and in `/usr/share/applications`? `/usr/local/share/applications`?

**Comment by sandeepbhardwaj** [comment]
Yes these are under ```/usr/local/share/applications/``` location

**Comment by cybre** [comment]
@sandeepbhardwaj Can you post the output of `cat /usr/local/share/applications/*libre* | grep Icon`, please?

**Comment by elmat0** [comment]
Just noticed [this](https://github.com/mank319/elementaryPlus/issues/297) duplicate bug.

**Comment by quassy** [comment]
Duplicate of #297, please continue posting there.
