### ISSUE TITLE
Icon Request: Viewnior

### ISSUE THREAD

**Issue by rootsandculture** [mank319/elementaryPlus#342]
A proper elementarized icon for Viewnoir would be nice :)

http://i.utdstc.com/icons/120/viewnior-0-7.png

**Comment by elmat0** [comment]
How's [this?](https://github.com/elmat0/icons_etc/blob/master/apps/128/viewnior.svg)
Could you also post the contents of the .desktop file?

**Comment by rootsandculture** [comment]
Looks good! 
Here's the content of /usr/local/share/applications/viewnior.desktop:
http://pastebin.com/tfG4RePV

**Comment by rootsandculture** [comment]
Thanks!
