### ISSUE TITLE
Indicator request: MEGAsync

### ISSUE THREAD

**Issue by aleksandar-todorovic** [mank319/elementaryPlus#35]
The default indicator looks pretty ugly and does not fit elementary style at all. Any chance for making a new white indicator?

**Comment by cybre** [comment]
This can't be done with the icon theme itself (QT indicators export their icons to /tmp/) but we have a set of monochrome icons and you can install them though the installer GUI.

**Comment by quassy** [comment]
@aleksandar-todorovic: Did you have success / any troubles running the script? (Closing as of now because the script should fix the original issue.)

**Comment by bil-elmoussaoui** [comment]
@quassy @cybre the third icon in the screenshot is a little bit blurry i guess 
![capture du 2015-05-18 17 42 26](https://cloud.githubusercontent.com/assets/7660997/7684302/4369a616-fd85-11e4-85db-e16f7f6c8635.png)

**Comment by aleksandar-todorovic** [comment]
@quassy Sorry for such a late response. Yup, I was able to fix this issue. Keep this issue closed. :)
