### ISSUE TITLE
Icon Request: VLC Player

### ISSUE THREAD

**Issue by svenkeeter** [mank319/elementaryPlus#352]

**Comment by cybre** [comment]
We already ship a VLC icon

**Comment by svenkeeter** [comment]
I meant the wingpanel icon frol VLC

**Comment by cybre** [comment]
We have that one as well
![screenshot from 2016-01-21 16 49 47](https://cloud.githubusercontent.com/assets/3101505/12485434/1683de62-c05f-11e5-871e-512e0cd78e21.png)

**Comment by svenkeeter** [comment]
Oh sorry! It is there. I am using Numix-Circle icon inheriting elementaryPlus. All other wingpanel icons are from elementaryPlus except VLC. Any idea how to fix it?

**Comment by cybre** [comment]
Can you post a screenshot of the current icon?

**Comment by svenkeeter** [comment]
![screenshot from 2016-01-21 18 14 33](https://cloud.githubusercontent.com/assets/13235528/12488248/fd84634e-c06a-11e5-895e-1fb0ffd4e914.png)

**Comment by cybre** [comment]
And the contents of your numix-circle index.theme?

**Comment by svenkeeter** [comment]
```
[Icon Theme]
Name=Numix Circle
Comment=Numix icon theme with a circular apps icons design

Inherits=elementaryPlus

Example=directory-x-normal

# Directory list
Directories=16x16/panel,22x22/panel,24x24/panel,48x48/apps,scalable/apps

[16x16/panel]
Size=16
Context=Panel
Type=Fixed

[22x22/panel]
Size=22
Context=Panel
Type=Fixed

[24x24/panel]
Size=24
Context=Panel
Type=Fixed

[48x48/apps]
Size=48
Context=Applications
Type=Fixed

[scalable/apps]
Size=16
Context=Applications
MinSize=8
MaxSize=512
Type=Scalable
```

**Comment by cybre** [comment]
Ok, what about the second question?

**Comment by svenkeeter** [comment]
I have the numix base as well. I installed the Numix icons from a ppa so when installing Numix-Circle it installed 3 other icon sets as well (Numix, Numix-Light, Numix-Circle, Numix-Circle-Light)

**Comment by cybre** [comment]
`sudo cp /usr/share/icons/elementaryPlus/status/24/vlc-panel.svg /usr/share/icons/Numix/24/panel`

**Comment by svenkeeter** [comment]
Thanks a lot! That worked. Closing this issue now.
