### ISSUE TITLE
Icon request: Icon for Zsnes (as well as a symlink to snes9x) needed

### ISSUE THREAD

**Issue by sergioad** [mank319/elementaryPlus#367]
Hello friends could you elaborate an icon for Zsnes as well as a symlink of the icon for snes9x?

![zsnes](https://cloud.githubusercontent.com/assets/5375145/12913150/918a3278-cee2-11e5-94f2-2341742ab325.png)
icon=zsnes

**Comment by TraumaD** [comment]
Do you know the icon names I have an icon already made I just need to know what names to link it to.

![snes9x](https://cloud.githubusercontent.com/assets/10608836/14407104/bf99b57e-fe82-11e5-8fa1-782bc8a534a6.png)

**Comment by sergioad** [comment]
thanks @TraumaD and pardon me because of not responding you, I was busy so I did not had the posibility to open github :smile:

**Comment by TraumaD** [comment]
@sergioad it's no problem. I totally understand. I was just being lazy anyway a quick google search answered my question. :smile:

**Comment by sergioad** [comment]
Ok, thank you very much :smile:

**Comment by sergioad** [comment]
I will consider suggesting VBA-M GNOME photos GNOME to-do and maybe (just maybe because the icons of these apps are hardcoded) Gens GS and FCEUX :smile:
