### ISSUE TITLE
Icon request: Hangouts

### ISSUE THREAD

**Issue by cassidyjames** [mank319/elementaryPlus#371]
The Google Hangouts Chrome extension installs a very flat icon that doesn't fit in with elementary icons.

**Comment by rhoconlinux** [comment]
the icon name for this one is:
 chrome-knipolnnllmklapflnccelgolnpehhpl-Default.svg

Cheers!

source: https://github.com/numixproject/numix-icon-theme-circle/issues/1233

**Comment by TraumaD** [comment]
Sorry messed up there with the Mega icon commits but here is a preview of the Icon I submitted for PR:
![hangouts](https://cloud.githubusercontent.com/assets/10608836/14407205/c1954732-fe85-11e5-93c2-67022631a54b.png)
