### ISSUE TITLE
Installation should be installed inside the elementary icon theme

### ISSUE THREAD

**Issue by Philip-Scott** [mank319/elementaryPlus#375]
Instead of having the icons be it's own theme, they should get installed in /usr/share/icons/elementary so the user doesn't need to change system themes :)

**Comment by rhoconlinux** [comment]
wel... that's not a good idea at all for several reasons. But first of all the reason is that this theme inherits the original elementary theme, allowing to receive updates (if there are some) on the original icons and adding those that are not.
Plus, is another icon theme, right? :P

**Comment by Philip-Scott** [comment]
Since it's part of the elementary theme, it makes scene for it to be installed in the same directory, and anyone using the default elementary theme would just get the icons applied to them. 

The elementary+ theme does not overwrite any system icons, so there wouldn't be a problem with either this or the official theme's update. 

Also like i said, it makes it so everything get's integrated faster without having to use third party tools to select the theme, or have problems when if you uninstall the theme the whole system breaks

**Comment by rhoconlinux** [comment]
well... indeed, you wouldn't be able to uninstall it (without removing elementary theme)... et voilà :)

**Comment by quassy** [comment]
I agree with @rhoconlinux. While we try not to overwrite any elementary icon, we can't be certain this is the case in the future, and mixing our work with the official elementary icon theme just feels like bad practice, there is a reason inheritage exists (elementary itself also inherits from hicolor). It would make manually removing elementary+ damn hard. Also at least on elementary you don't need any 3rd party tools, elementary+ Configurator (which is part of the PPA) supports changing the icon theme in one click.

**Comment by Philip-Scott** [comment]
Alright, sounds fair :) I'll close the issue then
