### ISSUE TITLE
Hipchat icon is broken

### ISSUE THREAD

**Issue by przemuh** [mank319/elementaryPlus#409]
I've tried everything but nothing works for me....Hipchat icon in tray is broken.

OS: Freya

![screenshot from 2016-08-06 14 38 02](https://cloud.githubusercontent.com/assets/3865478/17456784/a0103fb6-5be3-11e6-833f-c7453ffba11e.png)

**Comment by quassy** [comment]
elementary+ should include support for the Hipchat status indicator #71. Apparently this is a bug with many apps, you have to edit the desktop file `/usr/share/applications/hipchat.desktop` (or similar) and add a reference to Unity so it looks like this: 

    Exec=env XDG_CURRENT_DESKTOP=Unity /what/was/here/before/hipchat

[Taken from this reddit comment.](https://www.reddit.com/r/elementaryos/comments/4w4rx0/new_user_coming_from_xubuntu_how_can_i_fix_this/d6447q2) To avoid that changes get overwritten by updates you could also copy the edited desktop file to `~/.local/share/applications/`.

Please report back if this works for you :smile:

**Comment by przemuh** [comment]
Works like a charm :) after editing hipchat4.desktop in both places /usr/share/applications + ~/.local/share/applications :)
