### ISSUE TITLE
Matching Loki's colors when it shows dark icons

### ISSUE THREAD

**Issue by bmcclure** [mank319/elementaryPlus#423]
My elementaryPlus icons are always monochrome white. They fit in perfectly when I have a dark desktop wallpaper. However, at least in Loki, when I switch to a lighter colored background, my indicator icons and the other text at the top turns black. The icons from elementaryPlus stay white, however.

Is there a way to make it match Loki's icon colors regardless of which state its in?

**Comment by quassy** [comment]
Duplicate of #416 

Thanks for your report. I'm closing this issue as it is a duplicate of an existing bug report (no worries!).
