### ISSUE TITLE
Notification Error

### ISSUE THREAD

**Issue by julihermes** [mank319/elementaryPlus#46]
I try install install any icon and return this:

```
Installing patched sni-qt
Traceback (most recent call last):
  File "./scripts/elementaryplus-installer", line 166, in install
    notif.show()
gi._glib.GError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
```

I removed the three lines containing "notif.show()" and work for me, but not show any notification.

**Comment by cybre** [comment]
What system are you on?

**Comment by julihermes** [comment]
Elementary OS Freya Stable. See the screenshot!

![screenshot from 2015-04-20 08 42 47](https://cloud.githubusercontent.com/assets/6106903/7229385/5ef43c6e-e739-11e4-8306-92ea097eb504.png)

**Comment by cybre** [comment]
You're probably missing the Gobject Introspection libnotify library. I'm
not sure what the package name is, I'll check as soon as I come home. I'll
probably add a list of dependencies to the README file, too.

**Comment by julihermes** [comment]
so... any solution? :)
