### ISSUE TITLE
icon request: Oracle Java 8

### ISSUE THREAD

**Issue by julihermes** [mank319/elementaryPlus#48]

**Comment by julihermes** [comment]
So, i find this icon on DeviantArt (http://flakshack.deviantart.com/art/Java-Icon-356374131).
Maybe can help you.

**Comment by quassy** [comment]
Sadly I don't think this does fit the elementary style very well.

**Comment by mank319** [comment]
I agree. This is  too far from elementary's HIGs to be included. Maybe one of the creative folks might feel interested in creating an icon? @traumad91 or @fsvh maybe? :smile:

**Comment by quassy** [comment]
Maybe the [icon from elementary-add](https://github.com/varlesh/elementary-add/blob/master/elementary-add/apps/48/java.svg) could be used as base (only 48px atm). The mug should probably be a bit more visible.
