### ISSUE TITLE
Icon Request: Redshift

### ISSUE THREAD

**Issue by orschiro** [mank319/elementaryPlus#53]
[Redshift](https://github.com/jonls/redshift) adjusts the color temperature of your screen according to your surroundings and is thus a must-have tool for people who work a lot in front of their screen. It comes with the following indicator:

![image](https://cloud.githubusercontent.com/assets/170947/7228835/72e5077a-e75d-11e4-8a71-15c278b6d126.png)

**Comment by fsvh** [comment]
I just added the icon that I did yesterday, hope the pull request will be accepted. :)

![bulb](https://cloud.githubusercontent.com/assets/5596229/7229086/007e086e-e760-11e4-8cbb-86bdf63d461a.png)

**Comment by orschiro** [comment]
@fsvh 

That one looks great! Thanks a lot! What is the first from the left?

**Comment by fsvh** [comment]
it's caffeine icon

**Comment by orschiro** [comment]
Is that one also part of your pull request? Mine looks different.

![image](https://cloud.githubusercontent.com/assets/170947/7229846/8f1a37ca-e768-11e4-8185-2e2bd5bf5b0d.png)

**Comment by fsvh** [comment]
I don't because they already have the versioin that do you usinig. So i pull requested the redshift icon and synpase-indicator fixed.

**Comment by orschiro** [comment]
Got it. Thanks!

**Comment by quassy** [comment]
Closing this as I believe it was fixed with the [great contribution](https://github.com/mank319/elementaryPlus/commit/3e1564411dc62602666d7544b017c9306947d5db) of @fsvh :)

**Comment by fsvh** [comment]
@quassy I want to pull my version for caffeine. https://github.com/fsvh/freya-indicators
