### ISSUE TITLE
Uget indicator icon

### ISSUE THREAD

**Issue by bil-elmoussaoui** [mank319/elementaryPlus#72]
Hello everyone,
I would like to ask you to add a new icon for the uget indicator icon.

I have no idea about the icon line.
thanks!

**Comment by RafaelCz** [comment]
Here is my proposal:
![bildschirmfoto vom 2015-05-02 02 39 35](https://cloud.githubusercontent.com/assets/7204193/7439274/6b3c32b6-f075-11e4-82b4-be926c4833e2.png)
1. default
2. downloading
3 error

I used the generic download icon instead of their ugly and unbalanced logo.

**Comment by bil-elmoussaoui** [comment]
Looks fine to me !! 😎 hope it's will get merged

**Comment by mank319** [comment]
Thanks @RafaelCz for fixing this!
