### ISSUE TITLE
synpatic icon

### ISSUE THREAD

**Issue by fsvh** [mank319/elementaryPlus#77]
old
![image4723](https://cloud.githubusercontent.com/assets/5596229/7458475/f8a80d02-f294-11e4-84cf-8b9d637c792c.png)

new
![synaptic](https://cloud.githubusercontent.com/assets/5596229/7458476/fac460fe-f294-11e4-9df6-9305b03220dd.png)

I'm working on this icon but I'm not sure about the final result...

**Comment by quassy** [comment]
I'm not sure if this says "Synaptic" or "Package Manager" for me on first sight (the old one does not as well) :/

**Comment by quassy** [comment]
Maybe the [icon from elementary-add](https://github.com/varlesh/elementary-add/blob/master/elementary-add/apps/48/synaptic.svg) could be used as base (only 48px atm).

**Comment by bil-elmoussaoui** [comment]
The dev of Configurator have a ppa of elementary thirdparty apps icons https://launchpad.net/~l-admin-3/+archive/ubuntu/apps-daily/+packages and it's has a good icon of synaptic 
![capture du 2015-06-06 19 40 10](https://cloud.githubusercontent.com/assets/7660997/8020711/d2de78dc-0c83-11e5-99d5-fe3717be138c.png)

**Comment by quassy** [comment]
Strictly speaking that is not a 3rd party icon, it's a symlink to the icon of upcoming [AppCenter](https://launchpad.net/appcenter).

**Comment by quassy** [comment]
**This is a duplicate of #32, please continue the discussion there.**
