### ISSUE TITLE
Icon request: Google Music Manager

### ISSUE THREAD

**Issue by orschiro** [mank319/elementaryPlus#82]
Is someone able to make a nice white icon for [Google's Music Manager](http://www.google.de/linuxrepositories/)?

Below displayed with its original orange icon:
![image](https://cloud.githubusercontent.com/assets/170947/7588242/15ff8d12-f8bc-11e4-8bd1-2a70f0feae2e.png)

Thanks very much!

Robert

**Comment by RafaelCz** [comment]
Making an icon is not a problem, but changing is...
I tried to apply an alternative icon but I failed, it seems to be hard-coded in the binary.

**Comment by orschiro** [comment]
Bad news. Nevertheless thanks for trying your best!

**Comment by bil-elmoussaoui** [comment]
@quassy this is impossible to do, the same goes for google chrome. The icons are hardcoded in ```.pak``` files :/

**Comment by orschiro** [comment]
@bil-elmoussaoui 

I contacted the Google Music support with the request to comment on this discussion. 

> Dear developers, 
>
>I would like to pay your attention to the hard-coded icons used in the Linux version of the Google Music Manager. This means that in custom themes the tray icon of the Music Manager cannot be properly made compatible with the theme. 

>The issue is further described on Github: >https://github.com/mank319/elementaryPlus/issues/82#issuecomment-106479298

>I would very appreciate if any Google Music Manager developer for Linux could comment on our discussion. 

I submitted this on the help page to [Download & install Music Manager](https://support.google.com/googleplay/answer/1229970?hl=en#ts=4626485,4627544).
