### ISSUE TITLE
Some more indicators

### ISSUE THREAD

**Issue by bil-elmoussaoui** [mank319/elementaryPlus#91]
Hello,
I would like to ask you and especially @RafaelCz (as you've done almost all the indicators) if you can add those indicators too : 
- [ ] Touchpad indicator
- [ ] Pushbullet Indicator directory : opt/extras.ubuntu.com/pushbullet-indicator/share/pushbullet-indicator/icons
- [ ] My weather indicator  directory : opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/icons the icons are png (you can create svg icons and convert them using cairosvg in python)
- [x] Keepassx directory : /usr/share/keeppassx/icons ; the icons are png too! 
Those three are hardcoded (the icons are in /opt...)
- [ ] VLC 
- [x] Kazam
- [ ] Clementine
- [ ] Autokey icons are : autokey-status , autokey-status-dark, autokey-status-error
- [ ] Y-ppa-manager

The icons of pushbullet indicator and my weather indicator are pretty cool! the only issue that they're grey instead of white..
Thanks!

**Comment by bil-elmoussaoui** [comment]
I will close this and wait open separate issues for the indicators that i use

**Comment by quassy** [comment]
Individual issues are always the best :)
