### ISSUE TITLE
GNU PSPP icon

### ISSUE THREAD

**Issue by orschiro** [mank319/elementaryPlus#99]
Hi all, 

Is someone capable of making a [GNU PSPP](http://www.gnu.org/software/pspp/) icon that fits more to the eOS style?

In the below screenshot the default icon is the far right one:

![image](https://cloud.githubusercontent.com/assets/170947/7755749/d46675f4-fff6-11e4-9e96-a2212a120a3a.png)

Thankfully,

Robert

**Comment by quassy** [comment]
For reference, this is the logo of PSPP:
![Original icon](https://upload.wikimedia.org/wikipedia/commons/6/6d/Pspplogo.png)

**Comment by elmat0** [comment]
Here's a simple icon with a couple of colour options. Thoughts?
![Blue](https://rawgit.com/elmat0/icons_etc/8284ca404979a38c9ff98fbf04406b9b30f203b7/apps/128/pspp.svg) ![Colourful](https://rawgit.com/elmat0/icons_etc/8284ca404979a38c9ff98fbf04406b9b30f203b7/apps/128/pspp2.svg)

**Comment by cybre** [comment]
@elmat0 Looks great!

**Comment by cybre** [comment]
Not sure about the shadow, though.

**Comment by elmat0** [comment]
Yeah the shadow does look a bit off. Let us know which colour scheme you prefer (or make up another) and I'll fiddle with the shadow.

**Comment by cybre** [comment]
The second one is great.

**Comment by elmat0** [comment]
A little more convincing?
![pspp2 tweaked shadow](https://rawgit.com/elmat0/icons_etc/579342a58e6c50162244858eb29d2f4300680fb6/apps/128/pspp2.svg)

**Comment by orschiro** [comment]
@elmat0 

This one looks great!

**Comment by cybre** [comment]
@elmat0 Yes.
